version: '3.7'
services:
  db:
    image: postgres:12
    container_name: apisuite-db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_ADDITIONAL_DATABASES}
      - POSTGRES_SCHEMA
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - "5432:${POSTGRES_PORT_INTERNAL}"
    volumes:
      - ./.compose-utils/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.compose-utils/db/data:/var/lib/postgresql/data

  apisuite_jobs:
    image: cloudokihub/apisuite-be-jobs:latest
    container_name: apisuite-jobs
    environment:
      - APISUITE_JOBS_DB=${APISUITE_JOBS_DB}
      - APISUITE_JOBS_ACTV_CRON=${APISUITE_JOBS_ACTV_CRON}
      - APISUITE_JOBS_ACTV_TTL=${APISUITE_JOBS_ACTV_TTL}
      - APISUITE_JOBS_RECOV_CRON=${APISUITE_JOBS_RECOV_CRON}
      - APISUITE_JOBS_RECOV_TTL=${APISUITE_JOBS_RECOV_TTL}

  hydra-migrate:
    container_name: apisuite-hydra-migrate
    image: oryd/hydra:v1.6-alpine
    depends_on:
      - db
    environment:
      - DSN=${DSN}
    command:
      migrate sql -e --yes
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.6-alpine
    container_name: apisuite-hydra-server
    restart: unless-stopped
    depends_on:
      - hydra-migrate
      - db
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=${HYDRA_SERVER_URLS_SELF_ISSUER:-http://apisuite-hydra-server:4444}
      - URLS_CONSENT=${HYDRA_SERVER_URLS_CONSENT:-http://127.0.0.1:6001/auth/consent}
      - URLS_LOGIN=${HYDRA_SERVER_URLS_LOGIN:-http://127.0.0.1:6001/auth/login}
      - URLS_LOGOUT=${HYDRA_SERVER_URLS_LOGOUT:-http://127.0.0.1:6001/auth/logout}
      - DSN=${DSN}
      - SECRETS_SYSTEM=${SECRETS_SYSTEM}
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=${SECRETS_SYSTEM}
      - CORS_ALLOWED_ORIGINS=*
      - SERVE_PUBLIC_CORS_ENABLED=true
      - LOG_LEVEL=debug
      - SERVE_PUBLIC_CORS_DEBUG=true
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=*
      - SERVE_ADMIN_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_DEBUG=true
      - SERVE_ADMIN_CORS_ALLOWED_ORIGINS=*
      - SERVE_COOKIES_SAME_SITE_LEGACY_WORKAROUND=true

  apisuite_msg_broker:
    image: "rabbitmq:3.8.8-alpine"
    container_name: apisuite-msg-broker
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
    ports:
      - 127.0.0.1:5672:5672
      - 15672:15672
    volumes:
      - ./.compose-utils/rabbitmq/etc/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./.compose-utils/rabbitmq/data/:/var/lib/rabbitmq/

  kong-migrations:
    image: kong:2.3-alpine
    container_name: apisuite-kong-migrations
    depends_on:
      - db
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE
      - KONG_PG_USER
      - KONG_PG_PASSWORD
      - KONG_PG_HOST
      - KONG_PG_DATABASE
    restart: on-failure

  kong:
    image: kong:2.3-alpine
    container_name: apisuite-kong
    depends_on:
      - kong-migrations
    environment:
      - KONG_DATABASE
      - KONG_PG_USER
      - KONG_PG_PASSWORD
      - KONG_PG_HOST
      - KONG_PG_DATABASE
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
    ports:
      - "8000:8000"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  broker:
    image: confluentinc/cp-kafka:7.1.1
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    environment:
      KAFKA_BROKERCONNECT: broker:29092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    ports:
      - 9000:9000

  keydb:
    image: eqalpha/keydb:x86_64_v5.3.3
    container_name: keydb
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    volumes:
      - ./.compose-utils/keydb/redis.conf:/etc/keydb/redis.conf
      - ./.compose-utils/keydb/data:/data
    ports:
      - 6379:6379
    restart: unless-stopped
networks:
  default:
    name: apisuite-net