version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run: npm install
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - run: git pull
      - run: ./build.sh

workflows:
  version: 2
  build:
    jobs:
      - release:
          context: docker
          filters:
            branches:
              only:
                - main
      - build:
          context: docker
          filters:
            branches:
              only:
                - main
          requires:
            - release