version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: cp -r ../.ssh/ .
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  release:
    docker:
      - image: cimg/node:14.16
    steps:
      - attach_workspace:
          at: ~/
      - run: ./scripts/get_version.sh .orig_version
      - run: cp -r .ssh ../.ssh && rm -rf .ssh
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release
      - run: ./scripts/get_version.sh .new_version
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: ./.scripts/build.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - add_ssh_keys:
          fingerprints:
            - 31:96:89:eb:aa:ee:09:68:3a:6b:10:ad:d0:95:81:80
      - attach_workspace:
          at: ~/
      - run: ./.scripts/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          context: docker
          filters:
            branches:
              only:
                - develop
                - staging
                - production
          requires:
            - test
      - build:
          context: docker
          filters:
            branches:
              only:
                - develop
                - staging
                - production
          requires:
            - release
      - deploy:
          context: vmachines
          filters:
            branches:
              only:
                - develop
                - staging
                - production
          requires:
            - build
