version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:12.20.1
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - persist_to_workspace:
          root: /
          paths:
            - /

  release:
    docker:
      - image: cimg/node:12.20.1
    steps:
      - attach_workspace:
          at: /
#      - checkout
#      - run: npm install
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release --dry-run
#      - persist_to_workspace:
#          root: ~/
#          paths:
#            - project

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: ./build.sh

workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          context: docker
          filters:
            branches:
              only:
                - production
          requires:
            - test
#      - build:
#          context: docker
#          filters:
#            branches:
#              only:
#                - develop
#                - staging
#                - production
#          requires:
#            - release