#!/usr/bin/env bash

psql -v ON_ERROR_STOP=1 --username "postgres" -d "$POSTGRES_DB"  <<-EOSQL
     CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA;
     CREATE ROLE $POSTGRES_USERNAME noinherit login password '$POSTGRES_PASSWORD';
     GRANT ALL PRIVILEGES ON $POSTGRES_DB TO $POSTGRES_USERNAME;
EOSQL